name: Robot Framework Tests
on:
  push:
    branches:
      - learning_abhi  # Change this to your main branch name
    
jobs:
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: tarathep/robotframework-github-action@v1.0
      with:
        tests_dir: '${{ github.workspace }}/Tests'
        reports_dir: '${{ github.workspace }}/Tests'
